import { type DietaryFlags, type Per100g } from '../schema/nutrition';

export type MealSlotSeed = 'breakfast' | 'lunch' | 'dinner' | 'snack';

export type FoodSeed = {
  name: string;
  nameUr?: string;
  foodGroup: 'protein' | 'staple' | 'vegetable' | 'fruit' | 'dairy' | 'fat' | 'snack' | 'beverage';
  cuisineTags: string[];
  allergenTags: string[];
  allowedSlots: MealSlotSeed[];
  dietaryFlags: DietaryFlags;
  per100g: Per100g & { fiberG: number };
  costTier: 1 | 2 | 3;
  prepTimeMin: number;
  servingUnits: { name: string; grams: number }[];
};

const halal = (extra: Partial<DietaryFlags> = {}): DietaryFlags => ({
  halalStatus: 'HALAL',
  ...extra,
});

/**
 * Pilot starter food set — Pakistani coaching staples plus a breakfast-only pool.
 * Macro data cross-referenced with USDA FDC entries; flagged for a
 * nutrition-literate review pass before real clients depend on it (plan §20).
 */
export const FOOD_SEED: FoodSeed[] = [
  {
    name: 'Chicken breast (skinless, cooked)',
    nameUr: 'مرغی کا سینہ',
    foodGroup: 'protein',
    cuisineTags: ['general', 'pakistani'],
    allergenTags: [],
    allowedSlots: ['lunch', 'dinner'],
    dietaryFlags: halal(),
    per100g: { kcal: 165, proteinG: 31, fatG: 3.6, carbsG: 0, fiberG: 0 },
    costTier: 2,
    prepTimeMin: 20,
    servingUnits: [{ name: 'piece', grams: 120 }],
  },
  {
    name: 'Beef qeema (lean, cooked)',
    nameUr: 'قیمہ',
    foodGroup: 'protein',
    cuisineTags: ['pakistani'],
    allergenTags: [],
    allowedSlots: ['lunch', 'dinner'],
    dietaryFlags: halal({ containsBeef: true }),
    per100g: { kcal: 250, proteinG: 26, fatG: 17, carbsG: 0, fiberG: 0 },
    costTier: 2,
    prepTimeMin: 30,
    servingUnits: [{ name: 'cup', grams: 150 }],
  },
  {
    name: 'Daal masoor (cooked)',
    nameUr: 'دال مسور',
    foodGroup: 'protein',
    cuisineTags: ['pakistani'],
    allergenTags: [],
    allowedSlots: ['lunch', 'dinner'],
    dietaryFlags: halal({ vegetarian: true, vegan: true }),
    per100g: { kcal: 116, proteinG: 9, fatG: 0.4, carbsG: 20, fiberG: 8 },
    costTier: 1,
    prepTimeMin: 25,
    servingUnits: [{ name: 'cup', grams: 200 }],
  },
  {
    name: 'Daal chana (cooked)',
    nameUr: 'دال چنا',
    foodGroup: 'protein',
    cuisineTags: ['pakistani'],
    allergenTags: [],
    allowedSlots: ['lunch', 'dinner'],
    dietaryFlags: halal({ vegetarian: true, vegan: true }),
    per100g: { kcal: 164, proteinG: 8.9, fatG: 2.6, carbsG: 27, fiberG: 8 },
    costTier: 1,
    prepTimeMin: 30,
    servingUnits: [{ name: 'cup', grams: 200 }],
  },
  {
    name: 'Roti (whole wheat)',
    nameUr: 'روٹی',
    foodGroup: 'staple',
    cuisineTags: ['pakistani'],
    allergenTags: ['wheat_gluten'],
    allowedSlots: ['lunch'],
    dietaryFlags: halal({ vegetarian: true, vegan: true }),
    per100g: { kcal: 264, proteinG: 9, fatG: 4, carbsG: 51, fiberG: 7 },
    costTier: 1,
    prepTimeMin: 10,
    servingUnits: [{ name: 'roti', grams: 40 }],
  },
  {
    name: 'White rice (cooked)',
    nameUr: 'چاول',
    foodGroup: 'staple',
    cuisineTags: ['pakistani', 'general'],
    allergenTags: [],
    allowedSlots: ['lunch'],
    dietaryFlags: halal({ vegetarian: true, vegan: true }),
    per100g: { kcal: 130, proteinG: 2.7, fatG: 0.3, carbsG: 28, fiberG: 0.4 },
    costTier: 1,
    prepTimeMin: 15,
    servingUnits: [{ name: 'cup', grams: 160 }],
  },
  {
    name: 'Brown rice (cooked)',
    foodGroup: 'staple',
    cuisineTags: ['general'],
    allergenTags: [],
    allowedSlots: ['lunch'],
    dietaryFlags: halal({ vegetarian: true, vegan: true }),
    per100g: { kcal: 111, proteinG: 2.6, fatG: 0.9, carbsG: 23, fiberG: 1.8 },
    costTier: 2,
    prepTimeMin: 25,
    servingUnits: [{ name: 'cup', grams: 195 }],
  },
  {
    name: 'Egg (whole, boiled)',
    nameUr: 'انڈا',
    foodGroup: 'protein',
    cuisineTags: ['general'],
    allergenTags: ['egg'],
    allowedSlots: ['breakfast'],
    dietaryFlags: halal({ vegetarian: true }),
    per100g: { kcal: 155, proteinG: 13, fatG: 11, carbsG: 1.1, fiberG: 0 },
    costTier: 1,
    prepTimeMin: 10,
    servingUnits: [{ name: 'piece', grams: 50 }],
  },
  {
    name: 'Egg scrambled',
    nameUr: 'انڈے کی بھجیا',
    foodGroup: 'protein',
    cuisineTags: ['general'],
    allergenTags: ['egg'],
    allowedSlots: ['breakfast'],
    dietaryFlags: halal({ vegetarian: true }),
    per100g: { kcal: 166, proteinG: 11, fatG: 12, carbsG: 2, fiberG: 0 },
    costTier: 1,
    prepTimeMin: 8,
    servingUnits: [{ name: 'serving', grams: 100 }],
  },
  {
    name: 'Omelette',
    nameUr: 'آملیٹ',
    foodGroup: 'protein',
    cuisineTags: ['general'],
    allergenTags: ['egg'],
    allowedSlots: ['breakfast'],
    dietaryFlags: halal({ vegetarian: true }),
    per100g: { kcal: 154, proteinG: 11, fatG: 12, carbsG: 0.6, fiberG: 0 },
    costTier: 1,
    prepTimeMin: 10,
    servingUnits: [{ name: 'omelette', grams: 120 }],
  },
  {
    name: 'Greek yogurt (plain)',
    nameUr: 'دہی',
    foodGroup: 'dairy',
    cuisineTags: ['general'],
    allergenTags: ['milk'],
    allowedSlots: ['breakfast'],
    dietaryFlags: halal({ vegetarian: true }),
    per100g: { kcal: 59, proteinG: 10, fatG: 0.4, carbsG: 3.6, fiberG: 0 },
    costTier: 2,
    prepTimeMin: 0,
    servingUnits: [{ name: 'cup', grams: 245 }],
  },
  {
    name: 'Granola yogurt bowl',
    foodGroup: 'dairy',
    cuisineTags: ['general'],
    allergenTags: ['milk', 'wheat_gluten'],
    allowedSlots: ['breakfast'],
    dietaryFlags: halal({ vegetarian: true }),
    per100g: { kcal: 120, proteinG: 8, fatG: 3.5, carbsG: 16, fiberG: 2 },
    costTier: 2,
    prepTimeMin: 5,
    servingUnits: [{ name: 'bowl', grams: 250 }],
  },
  {
    name: 'Bran bread',
    foodGroup: 'staple',
    cuisineTags: ['general'],
    allergenTags: ['wheat_gluten'],
    allowedSlots: ['breakfast'],
    dietaryFlags: halal({ vegetarian: true, vegan: true }),
    per100g: { kcal: 247, proteinG: 13, fatG: 3.5, carbsG: 41, fiberG: 7 },
    costTier: 1,
    prepTimeMin: 0,
    servingUnits: [{ name: 'slice', grams: 35 }],
  },
  {
    name: 'Black coffee',
    foodGroup: 'beverage',
    cuisineTags: ['general'],
    allergenTags: [],
    allowedSlots: ['breakfast'],
    dietaryFlags: halal({ vegetarian: true, vegan: true }),
    per100g: { kcal: 2, proteinG: 0.1, fatG: 0, carbsG: 0, fiberG: 0 },
    costTier: 1,
    prepTimeMin: 5,
    servingUnits: [{ name: 'cup', grams: 240 }],
  },
  {
    name: 'Green tea',
    foodGroup: 'beverage',
    cuisineTags: ['general'],
    allergenTags: [],
    allowedSlots: ['breakfast'],
    dietaryFlags: halal({ vegetarian: true, vegan: true }),
    per100g: { kcal: 1, proteinG: 0, fatG: 0, carbsG: 0, fiberG: 0 },
    costTier: 1,
    prepTimeMin: 5,
    servingUnits: [{ name: 'cup', grams: 240 }],
  },
  {
    name: 'Chai with stevia',
    nameUr: 'چائے (اسٹیویا)',
    foodGroup: 'beverage',
    cuisineTags: ['pakistani'],
    allergenTags: ['milk'],
    allowedSlots: ['breakfast'],
    dietaryFlags: halal({ vegetarian: true }),
    per100g: { kcal: 18, proteinG: 1, fatG: 0.8, carbsG: 1.5, fiberG: 0 },
    costTier: 1,
    prepTimeMin: 8,
    servingUnits: [{ name: 'cup', grams: 200 }],
  },
  {
    name: 'Milk (full fat)',
    nameUr: 'دودھ',
    foodGroup: 'dairy',
    cuisineTags: ['general'],
    allergenTags: ['milk'],
    allowedSlots: ['snack'],
    dietaryFlags: halal({ vegetarian: true }),
    per100g: { kcal: 61, proteinG: 3.2, fatG: 3.3, carbsG: 4.8, fiberG: 0 },
    costTier: 1,
    prepTimeMin: 0,
    servingUnits: [{ name: 'glass', grams: 250 }],
  },
  {
    name: 'Paneer',
    nameUr: 'پنیر',
    foodGroup: 'dairy',
    cuisineTags: ['pakistani'],
    allergenTags: ['milk'],
    allowedSlots: ['lunch', 'dinner'],
    dietaryFlags: halal({ vegetarian: true }),
    per100g: { kcal: 265, proteinG: 18, fatG: 21, carbsG: 1.2, fiberG: 0 },
    costTier: 2,
    prepTimeMin: 15,
    servingUnits: [{ name: 'cube', grams: 30 }],
  },
  {
    name: 'Chapli kebab',
    nameUr: 'چپلی کباب',
    foodGroup: 'protein',
    cuisineTags: ['pakistani'],
    allergenTags: [],
    allowedSlots: ['lunch', 'dinner'],
    dietaryFlags: halal({ containsBeef: true }),
    per100g: { kcal: 280, proteinG: 16, fatG: 22, carbsG: 6, fiberG: 1 },
    costTier: 2,
    prepTimeMin: 25,
    servingUnits: [{ name: 'piece', grams: 100 }],
  },
  {
    name: 'Tilapia fillet (cooked)',
    nameUr: 'مچھلی',
    foodGroup: 'protein',
    cuisineTags: ['general'],
    allergenTags: ['fish'],
    allowedSlots: ['lunch', 'dinner'],
    dietaryFlags: halal(),
    per100g: { kcal: 96, proteinG: 20, fatG: 1.7, carbsG: 0, fiberG: 0 },
    costTier: 2,
    prepTimeMin: 20,
    servingUnits: [{ name: 'fillet', grams: 115 }],
  },
  {
    name: 'Chicken karahi',
    nameUr: 'چکن کڑاہی',
    foodGroup: 'protein',
    cuisineTags: ['pakistani'],
    allergenTags: [],
    allowedSlots: ['lunch', 'dinner'],
    dietaryFlags: halal(),
    per100g: { kcal: 190, proteinG: 17, fatG: 12, carbsG: 3, fiberG: 0.5 },
    costTier: 2,
    prepTimeMin: 40,
    servingUnits: [{ name: 'serving', grams: 200 }],
  },
  {
    name: 'Aloo sabzi',
    nameUr: 'آلو کی سبزی',
    foodGroup: 'vegetable',
    cuisineTags: ['pakistani'],
    allergenTags: [],
    allowedSlots: ['lunch', 'dinner'],
    dietaryFlags: halal({ vegetarian: true, vegan: true }),
    per100g: { kcal: 90, proteinG: 2, fatG: 4.5, carbsG: 11, fiberG: 2 },
    costTier: 1,
    prepTimeMin: 25,
    servingUnits: [{ name: 'serving', grams: 150 }],
  },
  {
    name: 'Bhindi masala',
    nameUr: 'بھنڈی',
    foodGroup: 'vegetable',
    cuisineTags: ['pakistani'],
    allergenTags: [],
    allowedSlots: ['lunch', 'dinner'],
    dietaryFlags: halal({ vegetarian: true, vegan: true }),
    per100g: { kcal: 80, proteinG: 2, fatG: 5, carbsG: 8, fiberG: 3.2 },
    costTier: 1,
    prepTimeMin: 25,
    servingUnits: [{ name: 'serving', grams: 150 }],
  },
  {
    name: 'Palak (cooked spinach)',
    nameUr: 'پالک',
    foodGroup: 'vegetable',
    cuisineTags: ['pakistani'],
    allergenTags: [],
    allowedSlots: ['lunch', 'dinner'],
    dietaryFlags: halal({ vegetarian: true, vegan: true }),
    per100g: { kcal: 41, proteinG: 2.9, fatG: 0.4, carbsG: 6.8, fiberG: 2.4 },
    costTier: 1,
    prepTimeMin: 20,
    servingUnits: [{ name: 'serving', grams: 150 }],
  },
  {
    name: 'Kachumber salad',
    nameUr: 'کچومر سلاد',
    foodGroup: 'vegetable',
    cuisineTags: ['pakistani'],
    allergenTags: [],
    allowedSlots: ['lunch', 'dinner'],
    dietaryFlags: halal({ vegetarian: true, vegan: true }),
    per100g: { kcal: 25, proteinG: 1, fatG: 0.2, carbsG: 5, fiberG: 1.5 },
    costTier: 1,
    prepTimeMin: 10,
    servingUnits: [{ name: 'bowl', grams: 120 }],
  },
  {
    name: 'Banana',
    nameUr: 'کیلا',
    foodGroup: 'fruit',
    cuisineTags: ['general'],
    allergenTags: [],
    allowedSlots: ['snack'],
    dietaryFlags: halal({ vegetarian: true, vegan: true }),
    per100g: { kcal: 89, proteinG: 1.1, fatG: 0.3, carbsG: 23, fiberG: 2.6 },
    costTier: 1,
    prepTimeMin: 0,
    servingUnits: [{ name: 'piece', grams: 118 }],
  },
  {
    name: 'Apple',
    nameUr: 'سیب',
    foodGroup: 'fruit',
    cuisineTags: ['general'],
    allergenTags: [],
    allowedSlots: ['snack'],
    dietaryFlags: halal({ vegetarian: true, vegan: true }),
    per100g: { kcal: 52, proteinG: 0.3, fatG: 0.2, carbsG: 14, fiberG: 2.4 },
    costTier: 1,
    prepTimeMin: 0,
    servingUnits: [{ name: 'piece', grams: 180 }],
  },
  {
    name: 'Almonds',
    nameUr: 'بادام',
    foodGroup: 'fat',
    cuisineTags: ['general'],
    allergenTags: ['tree_nut'],
    allowedSlots: ['lunch', 'snack'],
    dietaryFlags: halal({ vegetarian: true, vegan: true }),
    per100g: { kcal: 579, proteinG: 21, fatG: 50, carbsG: 22, fiberG: 12.5 },
    costTier: 3,
    prepTimeMin: 0,
    servingUnits: [{ name: 'handful', grams: 28 }],
  },
  {
    name: 'Peanut butter',
    foodGroup: 'fat',
    cuisineTags: ['general'],
    allergenTags: ['peanut'],
    allowedSlots: ['snack'],
    dietaryFlags: halal({ vegetarian: true, vegan: true }),
    per100g: { kcal: 588, proteinG: 25, fatG: 50, carbsG: 20, fiberG: 6 },
    costTier: 2,
    prepTimeMin: 0,
    servingUnits: [{ name: 'tbsp', grams: 16 }],
  },
  {
    name: 'Olive oil',
    foodGroup: 'fat',
    cuisineTags: ['general'],
    allergenTags: [],
    allowedSlots: ['lunch', 'snack'],
    dietaryFlags: halal({ vegetarian: true, vegan: true }),
    per100g: { kcal: 884, proteinG: 0, fatG: 100, carbsG: 0, fiberG: 0 },
    costTier: 2,
    prepTimeMin: 0,
    servingUnits: [{ name: 'tbsp', grams: 13.5 }],
  },
  {
    name: 'Desi ghee',
    nameUr: 'دیسی گھی',
    foodGroup: 'fat',
    cuisineTags: ['pakistani'],
    allergenTags: ['milk'],
    allowedSlots: ['lunch'],
    dietaryFlags: halal({ vegetarian: true }),
    per100g: { kcal: 900, proteinG: 0, fatG: 100, carbsG: 0, fiberG: 0 },
    costTier: 2,
    prepTimeMin: 0,
    servingUnits: [{ name: 'tsp', grams: 4.2 }],
  },
  {
    name: 'Oats (dry)',
    foodGroup: 'staple',
    cuisineTags: ['general'],
    allergenTags: [],
    allowedSlots: ['breakfast'],
    dietaryFlags: halal({ vegetarian: true, vegan: true }),
    per100g: { kcal: 389, proteinG: 16.9, fatG: 6.9, carbsG: 66, fiberG: 10.6 },
    costTier: 1,
    prepTimeMin: 10,
    servingUnits: [{ name: 'cup', grams: 80 }],
  },
  {
    name: 'Dates (khajoor)',
    nameUr: 'کھجور',
    foodGroup: 'snack',
    cuisineTags: ['pakistani'],
    allergenTags: [],
    allowedSlots: ['snack'],
    dietaryFlags: halal({ vegetarian: true, vegan: true }),
    per100g: { kcal: 277, proteinG: 1.8, fatG: 0.2, carbsG: 75, fiberG: 6.7 },
    costTier: 2,
    prepTimeMin: 0,
    servingUnits: [{ name: 'piece', grams: 7.1 }],
  },
];
